Great progress on war turn handler and lucky selector

diff --git a/game_engine_dev/game/test_drivers/combat_mng_comp b/game_engine_dev/game/test_drivers/combat_mng_comp
--- a/game_engine_dev/game/test_drivers/combat_mng_comp
+++ b/game_engine_dev/game/test_drivers/combat_mng_comp
@@ -9,11 +9,26 @@ if [ ! -f "$LIB_SO" ]; then
     exit 1
 fi
 
+IMPL_MK="${1:-${COMBAT_MNG_MK:-mk02}}"
+case "$IMPL_MK" in
+    mk1) IMPL_MK=mk01 ;;
+    mk2) IMPL_MK=mk02 ;;
+esac
+IMPL_REL="impl/combat_mng_impl_${IMPL_MK}.cpp"
+IMPL_ABS="../${IMPL_REL}"
+if [ ! -f "$IMPL_ABS" ]; then
+    echo "missing impl $IMPL_ABS (usage: ./combat_mng_comp [mk1|mk2|mk01|mk02])"
+    exit 1
+fi
+
 INC="-I.. -I../.. -I../../misc -I../../data_io -I../../static_state -I../../dyn_state \
      -I../../map_loader -I../../adv_map_gen -I../../simple_map_gen \
      -I../../city -I../../city/effector -I../../city/assessor -I../../gen_bit_banks \
-     -I../../ai_pathing/walk_general -I../../gen_effector -I../../ai_proc"
+     -I../../ai_pathing/walk_general -I../../ai_pathing/walk_cities \
+     -I../../gen_effector -I../../ai_proc"
 CXXFLAGS="-std=c++17 -Wall -Wextra"
+CXXFLAGS="$CXXFLAGS -DCOMBAT_MNG_IMPL=\"${IMPL_REL}\""
+CXXFLAGS="$CXXFLAGS -DCOMBAT_MNG_MK=\"${IMPL_MK}\""
 
 g++ $CXXFLAGS $INC -c ../../data_io/runtime_static_loader.cpp -o runtime_static_loader.o
 g++ $CXXFLAGS $INC -c ../../map_loader/map_terrain_validate.cpp -o map_terrain_validate.o
@@ -29,9 +44,12 @@ g++ $CXXFLAGS $INC -c ../civ_relations.cpp -o civ_relations.o
 g++ $CXXFLAGS $INC -c ../city_array.cpp -o city_array.o
 g++ $CXXFLAGS $INC -c ../player_ledger.cpp -o player_ledger.o
 g++ $CXXFLAGS $INC -c ../tile_yields.cpp -o tile_yields.o
+g++ $CXXFLAGS $INC -c ../worker_helper.cpp -o worker_helper.o
+g++ $CXXFLAGS $INC -c ../unit_roster_mng.cpp -o unit_roster_mng.o
 g++ $CXXFLAGS $INC -c ../../misc/map_bit_array_overlay.cpp -o map_bit_array_overlay.o
 g++ $CXXFLAGS $INC -c ../../misc/map_bit_overlay.cpp -o map_bit_overlay.o
 g++ $CXXFLAGS $INC -c ../../misc/bit_array.cpp -o bit_array.o
+g++ $CXXFLAGS $INC -c ../../misc/assert_log.cpp -o assert_log.o
 g++ $CXXFLAGS $INC -c ../../gen_bit_banks/general_bit_bank.cpp -o general_bit_bank.o
 g++ $CXXFLAGS $INC -c ../../city/assessor/general_assessor.cpp -o general_assessor.o
 g++ $CXXFLAGS $INC -c ../../city/effect_ctx.cpp -o effect_ctx.o
@@ -48,6 +66,9 @@ g++ $CXXFLAGS $INC -c ../../city/effector/local_commerce_booster_register.cpp -o
 g++ $CXXFLAGS $INC -c ../../city/effector/city_pop_growth_booster_register.cpp -o city_pop_growth_booster_register.o
 g++ $CXXFLAGS $INC -c ../../city/effector/civ_pop_growth_booster_register.cpp -o civ_pop_growth_booster_register.o
 g++ $CXXFLAGS $INC -c ../../city/effector/city_culture_booster_register.cpp -o city_culture_booster_register.o
+g++ $CXXFLAGS $INC -c ../../city/effector/city_sanitation_booster_register.cpp -o city_sanitation_booster_register.o
+g++ $CXXFLAGS $INC -c ../../city/effector/civ_sanitation_booster_register.cpp -o civ_sanitation_booster_register.o
+g++ $CXXFLAGS $INC -c ../../city/effector/booster_register_link_stubs.cpp -o booster_register_link_stubs.o
 g++ $CXXFLAGS $INC -c ../../city/city.cpp -o city.o
 g++ $CXXFLAGS $INC -c ../../city/city_border.cpp -o city_border.o
 g++ $CXXFLAGS $INC -c ../../city/circular_tile_areas.cpp -o circular_tile_areas.o
@@ -62,6 +83,8 @@ g++ $CXXFLAGS $INC -c ../../dyn_state/shipyard_add_vector.cpp -o shipyard_add_ve
 g++ $CXXFLAGS $INC -c ../../dyn_state/trade_post_add_vector.cpp -o trade_post_add_vector.o
 g++ $CXXFLAGS $INC -c ../../ai_pathing/walk_general/sector_network.cpp -o sector_network.o
 g++ $CXXFLAGS $INC -c ../../ai_pathing/walk_general/sector_network_router.cpp -o sector_network_router.o
+g++ $CXXFLAGS $INC -c ../../ai_pathing/walk_cities/city_network.cpp -o city_network.o
+g++ $CXXFLAGS $INC -c ../../game_eval/test_drivers/player_muster_gen_ai_stubs.cpp -o gen_ai_stubs.o
 g++ $CXXFLAGS $INC -c combat_mng_tester.cpp -o combat_mng_tester.o
 
 g++ $CXXFLAGS -o combat_mng_tester \
@@ -79,9 +102,12 @@ g++ $CXXFLAGS -o combat_mng_tester \
     city_array.o \
     player_ledger.o \
     tile_yields.o \
+    worker_helper.o \
+    unit_roster_mng.o \
     map_bit_array_overlay.o \
     map_bit_overlay.o \
     bit_array.o \
+    assert_log.o \
     general_bit_bank.o \
     general_assessor.o \
     effect_ctx.o \
@@ -98,6 +124,9 @@ g++ $CXXFLAGS -o combat_mng_tester \
     city_pop_growth_booster_register.o \
     civ_pop_growth_booster_register.o \
     city_culture_booster_register.o \
+    city_sanitation_booster_register.o \
+    civ_sanitation_booster_register.o \
+    booster_register_link_stubs.o \
     city.o \
     city_border.o \
     circular_tile_areas.o \
@@ -112,11 +141,15 @@ g++ $CXXFLAGS -o combat_mng_tester \
     trade_post_add_vector.o \
     sector_network.o \
     sector_network_router.o \
+    city_network.o \
+    gen_ai_stubs.o \
     combat_mng_tester.o \
     -ldl \
     $LIB_SO \
-    -Wl,-rpath,'$ORIGIN/../../data_io'
+    -Wl,-rpath,'$ORIGIN/../../data_io' \
+    -Wl,--allow-multiple-definition
 
+echo "--- running combat_mng_tester (${IMPL_MK}) ---"
 ./combat_mng_tester
 EC=$?
 
