Added sanitation and much else

diff --git a/game_engine_dev/ai_pathing/walk_river/walk_river_mk1_start_comp b/game_engine_dev/ai_pathing/walk_river/walk_river_mk1_start_comp
--- a/game_engine_dev/ai_pathing/walk_river/walk_river_mk1_start_comp
+++ b/game_engine_dev/ai_pathing/walk_river/walk_river_mk1_start_comp
@@ -1,8 +1,15 @@
 #!/bin/bash
 
-INC="-I.. -I../.. -I../../game -I../../map_loader -I../../simple_map_gen -I../../misc"
+LIB_SO="../../data_io/runtime_static_loader_lib.so"
+if [ ! -f "$LIB_SO" ]; then
+    echo "missing $LIB_SO - run ../../data_io/runtime_static_loader_lib_comp first"
+    exit 1
+fi
+
+INC="-I.. -I../.. -I../../game -I../../map_loader -I../../simple_map_gen -I../../misc -I../../data_io -I../../static_state"
 CXXFLAGS="-std=c++17 -Wall -Wextra"
 
+g++ $CXXFLAGS $INC -c ../../data_io/runtime_static_loader.cpp -o runtime_static_loader.o
 g++ $CXXFLAGS $INC -c ../../map_loader/map_terrain_validate.cpp -o map_terrain_validate.o
 g++ $CXXFLAGS $INC -c ../../map_loader/map_terrain_data.cpp -o map_terrain_data.o
 g++ $CXXFLAGS $INC -c ../../map_loader/map_loader.cpp -o map_loader.o
@@ -17,6 +24,7 @@ g++ $CXXFLAGS $INC -c walk_river_mk1.cpp -o walk_river_mk1.o
 g++ $CXXFLAGS $INC -c walk_river_mk1_start_tester.cpp -o walk_river_mk1_start_tester.o
 
 g++ $CXXFLAGS -o walk_river_mk1_start_tester \
+    runtime_static_loader.o \
     map_terrain_validate.o \
     map_terrain_data.o \
     map_loader.o \
@@ -28,9 +36,12 @@ g++ $CXXFLAGS -o walk_river_mk1_start_tester \
     path_mk1.o \
     river_pathing.o \
     walk_river_mk1.o \
-    walk_river_mk1_start_tester.o
+    walk_river_mk1_start_tester.o \
+    -ldl \
+    $LIB_SO \
+    -Wl,-rpath,'$ORIGIN/../../data_io'
 
-rm map_terrain_validate.o map_terrain_data.o map_loader.o runtime_trace_dbg.o \
+rm runtime_static_loader.o map_terrain_validate.o map_terrain_data.o map_loader.o runtime_trace_dbg.o \
     game_array_simple.o factory_game_array_simple.o map_bit_overlay.o \
     ai_whiteboard.o path_mk1.o river_pathing.o \
     walk_river_mk1.o walk_river_mk1_start_tester.o
diff --git a/game_engine_dev/ai_pathing/walk_target/generate_distance_p2p_mk4_minor_ctrl_comp b/game_engine_dev/ai_pathing/walk_target/generate_distance_p2p_mk4_minor_ctrl_comp
--- a/game_engine_dev/ai_pathing/walk_target/generate_distance_p2p_mk4_minor_ctrl_comp
+++ b/game_engine_dev/ai_pathing/walk_target/generate_distance_p2p_mk4_minor_ctrl_comp
@@ -1,8 +1,18 @@
 #!/bin/bash
+set -e
 
-INC="-I. -I.. -I../.. -I../../game -I../../map_loader -I../../simple_map_gen -I../../misc -I../../ai_proc"
+cd "$(dirname "$0")"
+
+LIB_SO="../../data_io/runtime_static_loader_lib.so"
+if [ ! -f "$LIB_SO" ]; then
+    echo "missing $LIB_SO - run ../../data_io/runtime_static_loader_lib_comp first"
+    exit 1
+fi
+
+INC="-I. -I.. -I../.. -I../../game -I../../map_loader -I../../simple_map_gen -I../../misc -I../../ai_proc -I../../data_io -I../../static_state"
 CXXFLAGS="-std=c++17 -Wall -Wextra"
 
+g++ $CXXFLAGS $INC -c ../../data_io/runtime_static_loader.cpp -o runtime_static_loader.o
 g++ $CXXFLAGS $INC -c ../../game/runtime_trace_dbg.cpp -o runtime_trace_dbg.o
 g++ $CXXFLAGS $INC -c generate_distance_p2p_mk4.cpp -o generate_distance_p2p_mk4.o
 g++ $CXXFLAGS $INC -c walk_p2p_mk4.cpp -o walk_p2p_mk4.o
@@ -11,12 +21,13 @@ g++ $CXXFLAGS $INC -c ../../ai_proc/wb_que_xy.cpp -o wb_que_xy.o
 g++ $CXXFLAGS $INC -c generate_distance_p2p_mk4_minor_ctrl_tester.cpp -o generate_distance_p2p_mk4_minor_ctrl_tester.o
 
 g++ $CXXFLAGS -o generate_distance_p2p_mk4_minor_ctrl_tester \
+    runtime_static_loader.o \
     runtime_trace_dbg.o \
     generate_distance_p2p_mk4.o \
     walk_p2p_mk4.o \
     ai_whiteboard.o \
     wb_que_xy.o \
-    generate_distance_p2p_mk4_minor_ctrl_tester.o -lm
+    generate_distance_p2p_mk4_minor_ctrl_tester.o -lm -ldl
 
-rm runtime_trace_dbg.o generate_distance_p2p_mk4.o walk_p2p_mk4.o \
+rm runtime_static_loader.o runtime_trace_dbg.o generate_distance_p2p_mk4.o walk_p2p_mk4.o \
     ai_whiteboard.o wb_que_xy.o generate_distance_p2p_mk4_minor_ctrl_tester.o
diff --git a/game_engine_dev/ai_pathing/walk_target/generate_distance_to_ocean_coast_tm_comp b/game_engine_dev/ai_pathing/walk_target/generate_distance_to_ocean_coast_tm_comp
--- a/game_engine_dev/ai_pathing/walk_target/generate_distance_to_ocean_coast_tm_comp
+++ b/game_engine_dev/ai_pathing/walk_target/generate_distance_to_ocean_coast_tm_comp
@@ -1,8 +1,18 @@
 #!/bin/bash
+set -e
 
-INC="-I. -I.. -I../.. -I../../game -I../../map_loader -I../../simple_map_gen -I../../misc -I../../ai_proc"
+cd "$(dirname "$0")"
+
+LIB_SO="../../data_io/runtime_static_loader_lib.so"
+if [ ! -f "$LIB_SO" ]; then
+    echo "missing $LIB_SO - run ../../data_io/runtime_static_loader_lib_comp first"
+    exit 1
+fi
+
+INC="-I. -I.. -I../.. -I../../game -I../../map_loader -I../../simple_map_gen -I../../misc -I../../ai_proc -I../../data_io -I../../static_state"
 CXXFLAGS="-std=c++17 -Wall -Wextra"
 
+g++ $CXXFLAGS $INC -c ../../data_io/runtime_static_loader.cpp -o runtime_static_loader.o
 g++ $CXXFLAGS $INC -c ../../map_loader/map_terrain_validate.cpp -o map_terrain_validate.o
 g++ $CXXFLAGS $INC -c ../../map_loader/map_terrain_data.cpp -o map_terrain_data.o
 g++ $CXXFLAGS $INC -c ../../map_loader/map_loader.cpp -o map_loader.o
@@ -13,6 +23,7 @@ g++ $CXXFLAGS $INC -c ../../ai_proc/wb_que_xy.cpp -o wb_que_xy.o
 g++ $CXXFLAGS $INC -c generate_distance_to_ocean_coast_tm_tester.cpp -o generate_distance_to_ocean_coast_tm_tester.o
 
 g++ $CXXFLAGS -o generate_distance_to_ocean_coast_tm_tester \
+    runtime_static_loader.o \
     map_terrain_validate.o \
     map_terrain_data.o \
     map_loader.o \
@@ -20,8 +31,8 @@ g++ $CXXFLAGS -o generate_distance_to_ocean_coast_tm_tester \
     generate_distance_to_ocean_coast.o \
     ai_whiteboard.o \
     wb_que_xy.o \
-    generate_distance_to_ocean_coast_tm_tester.o
+    generate_distance_to_ocean_coast_tm_tester.o -ldl
 
-rm map_terrain_validate.o map_terrain_data.o map_loader.o \
+rm runtime_static_loader.o map_terrain_validate.o map_terrain_data.o map_loader.o \
     generate_distance_to_ocean_coast_tm.o generate_distance_to_ocean_coast.o \
     ai_whiteboard.o wb_que_xy.o generate_distance_to_ocean_coast_tm_tester.o
diff --git a/game_engine_dev/ai_proc/distant_explore/distant_explore_comp b/game_engine_dev/ai_proc/distant_explore/distant_explore_comp
--- a/game_engine_dev/ai_proc/distant_explore/distant_explore_comp
+++ b/game_engine_dev/ai_proc/distant_explore/distant_explore_comp
@@ -1,8 +1,15 @@
 #!/bin/bash
 
-INC="-I.. -I../.. -I../../game -I../../map_loader -I../../simple_map_gen -I../../misc -I../distant_explore -I../../ai_pathing -I../../ai_pathing/walk_target"
+LIB_SO="../../data_io/runtime_static_loader_lib.so"
+if [ ! -f "$LIB_SO" ]; then
+    echo "missing $LIB_SO - run ../../data_io/runtime_static_loader_lib_comp first"
+    exit 1
+fi
+
+INC="-I.. -I../.. -I../../game -I../../map_loader -I../../simple_map_gen -I../../misc -I../distant_explore -I../../ai_pathing -I../../ai_pathing/walk_target -I../../data_io -I../../static_state"
 CXXFLAGS="-std=c++17 -Wall -Wextra"
 
+g++ $CXXFLAGS $INC -c ../../data_io/runtime_static_loader.cpp -o runtime_static_loader.o
 g++ $CXXFLAGS $INC -c ../../map_loader/map_terrain_validate.cpp -o map_terrain_validate.o
 g++ $CXXFLAGS $INC -c ../../map_loader/map_terrain_data.cpp -o map_terrain_data.o
 g++ $CXXFLAGS $INC -c ../../map_loader/map_loader.cpp -o map_loader.o
@@ -21,6 +28,7 @@ g++ $CXXFLAGS $INC -c explore_distant_tester.cpp -o explore_distant_tester.o
 g++ $CXXFLAGS $INC -c explore_distant_mk3_tester.cpp -o explore_distant_mk3_tester.o
 
 g++ $CXXFLAGS -o explore_distant_tester \
+    runtime_static_loader.o \
     map_terrain_validate.o \
     map_terrain_data.o \
     map_loader.o \
@@ -31,9 +39,13 @@ g++ $CXXFLAGS -o explore_distant_tester \
     ai_whiteboard.o \
     explore_distant_mk1.o \
     explore_distant_mk2.o \
-    explore_distant_tester.o
+    explore_distant_tester.o \
+    -ldl \
+    $LIB_SO \
+    -Wl,-rpath,'$ORIGIN/../../data_io'
 
 g++ $CXXFLAGS -o explore_distant_mk3_tester \
+    runtime_static_loader.o \
     map_terrain_validate.o \
     map_terrain_data.o \
     map_loader.o \
@@ -47,9 +59,12 @@ g++ $CXXFLAGS -o explore_distant_mk3_tester \
     generate_distance_to_coastal_point.o \
     near_path_mk1.o \
     explore_distant_mk3.o \
-    explore_distant_mk3_tester.o
+    explore_distant_mk3_tester.o \
+    -ldl \
+    $LIB_SO \
+    -Wl,-rpath,'$ORIGIN/../../data_io'
 
-rm map_terrain_validate.o map_terrain_data.o map_loader.o runtime_trace_dbg.o \
+rm runtime_static_loader.o map_terrain_validate.o map_terrain_data.o map_loader.o runtime_trace_dbg.o \
     game_array_simple.o factory_game_array_simple.o map_bit_overlay.o \
     ai_whiteboard.o explore_distant_mk1.o explore_distant_mk2.o explore_distant_mk3.o \
     generate_distance_to_ocean_coast.o generate_distance_to_coastal_point.o near_path_mk1.o \
