Finished effectors

diff --git a/game_engine_dev/city/city_comp b/game_engine_dev/city/city_comp
--- a/game_engine_dev/city/city_comp
+++ b/game_engine_dev/city/city_comp
@@ -1,77 +1,107 @@
 #!/bin/bash
+set -e
 
-# Define the include path for the compiler
+cd "$(dirname "$0")"
+
+LIB_SO="../data_io/runtime_static_loader_lib.so"
+if [ ! -f "$LIB_SO" ]; then
+    echo "missing $LIB_SO - run ../data_io/runtime_static_loader_lib_comp first"
+    exit 1
+fi
+
 INC="-I../ \
      -I../misc \
      -I../data_io \
-     -I../wonders \
+     -I../static_state \
      -I../city \
-     -I../small_wonders \
-     -I../units \
-     -I../buildings"
+     -I../city/effector \
+     -I../dyn_state \
+     -I../gen_bit_banks \
+     -I../game \
+     -Iassessor \
+     -I../map_loader \
+     -I../adv_map_gen \
+     -I../simple_map_gen"
+CXXFLAGS="-std=c++17 -Wall -Wextra"
 
-# Compile dependencies
-g++ $INC -c ../misc/str_mng.cpp -o str_mng.o
-g++ $INC -c ../misc/bit_array.cpp -o bit_array.o
-g++ $INC -c ../data_io/tech_data.cpp -o tech_data.o
-g++ $INC -c ../data_io/resource_data.cpp -o resource_data.o
-g++ $INC -c ../data_io/building_data.cpp -o building_data.o
-g++ $INC -c ../data_io/city_flags.cpp -o city_flags.o
-g++ $INC -c ../data_io/wonder_data.cpp -o wonder_data.o
-g++ $INC -c ../data_io/small_wonder_data.cpp -o small_wonder_data.o
-g++ $INC -c ../data_io/unit_data.cpp -o unit_data.o
-g++ $INC -c ../buildings/building_vector.cpp -o building_vector.o
-g++ $INC -c ../wonders/wonder_vector.cpp -o wonder_vector.o
-g++ $INC -c ../small_wonders/small_wonder_vector.cpp -o small_wonder_vector.o
-g++ $INC -c ../units/unit_vector.cpp -o unit_vector.o
-g++ $INC -c building_assessor.cpp -o building_assessor.o
-g++ $INC -c wonder_assessor.cpp -o wonder_assessor.o
-g++ $INC -c small_wonder_assessor.cpp -o small_wonder_assessor.o
-g++ $INC -c unit_assessor.cpp -o unit_assessor.o
-g++ $INC -c city.cpp -o city.o
-g++ $INC -c city_tester.cpp -o city_tester.o
+g++ $CXXFLAGS $INC -c ../data_io/runtime_static_loader.cpp -o runtime_static_loader.o
+g++ $CXXFLAGS $INC -c ../misc/bit_array.cpp -o bit_array.o
+g++ $CXXFLAGS $INC -c ../misc/map_bit_overlay.cpp -o map_bit_overlay.o
+g++ $CXXFLAGS $INC -c ../misc/map_bit_array_overlay.cpp -o map_bit_array_overlay.o
+g++ $CXXFLAGS $INC -c ../map_loader/map_terrain_validate.cpp -o map_terrain_validate.o
+g++ $CXXFLAGS $INC -c ../map_loader/map_terrain_data.cpp -o map_terrain_data.o
+g++ $CXXFLAGS $INC -c ../map_loader/map_loader.cpp -o map_loader.o
+g++ $CXXFLAGS $INC -c ../game/runtime_trace_dbg.cpp -o runtime_trace_dbg.o
+g++ $CXXFLAGS $INC -c ../gen_bit_banks/general_bit_bank.cpp -o general_bit_bank.o
+g++ $CXXFLAGS $INC -c assessor/general_assessor.cpp -o general_assessor.o
+g++ $CXXFLAGS $INC -c effect_ctx.cpp -o effect_ctx.o
+g++ $CXXFLAGS $INC -c effector/effect_enabler.cpp -o effect_enabler.o
+g++ $CXXFLAGS $INC -c effector/booster_effect_register.cpp -o booster_effect_register.o
+g++ $CXXFLAGS $INC -c effector/local_unit_exp_booster_register.cpp -o local_unit_exp_booster_register.o
+g++ $CXXFLAGS $INC -c effector/civ_ship_training_booster_register.cpp -o civ_ship_training_booster_register.o
+g++ $CXXFLAGS $INC -c effector/city_commerce_booster_register.cpp -o city_commerce_booster_register.o
+g++ $CXXFLAGS $INC -c ../dyn_state/fort_add_vector.cpp -o fort_add_vector.o
+g++ $CXXFLAGS $INC -c ../dyn_state/mine_add_vector.cpp -o mine_add_vector.o
+g++ $CXXFLAGS $INC -c ../dyn_state/monastery_add_vector.cpp -o monastery_add_vector.o
+g++ $CXXFLAGS $INC -c ../dyn_state/outpost_add_vector.cpp -o outpost_add_vector.o
+g++ $CXXFLAGS $INC -c ../dyn_state/plantation_add_vector.cpp -o plantation_add_vector.o
+g++ $CXXFLAGS $INC -c ../dyn_state/shipyard_add_vector.cpp -o shipyard_add_vector.o
+g++ $CXXFLAGS $INC -c ../dyn_state/trade_post_add_vector.cpp -o trade_post_add_vector.o
+g++ $CXXFLAGS $INC -c ../dyn_state/unit_add_vector.cpp -o unit_add_vector.o
+g++ $CXXFLAGS $INC -c ../dyn_state/unit_movement_mng.cpp -o unit_movement_mng.o
+g++ $CXXFLAGS $INC -c ../game/game_array_simple.cpp -o game_array_simple.o
+g++ $CXXFLAGS $INC -c ../game/factory_game_array_simple.cpp -o factory_game_array_simple.o
+g++ $CXXFLAGS $INC -c ../game/game_state.cpp -o game_state.o
+g++ $CXXFLAGS $INC -c ../game/player_ledger.cpp -o player_ledger.o
+g++ $CXXFLAGS $INC -c ../game/civ_relations.cpp -o civ_relations.o
+g++ $CXXFLAGS $INC -c ../game/city_array.cpp -o city_array.o
+g++ $CXXFLAGS $INC -c city.cpp -o city.o
+g++ $CXXFLAGS $INC -c city_tester.cpp -o city_tester.o
 
-# Link everything into the final tester
-g++ -o \
-    city_tester \
-    str_mng.o \
+g++ $CXXFLAGS -o city_tester \
+    runtime_static_loader.o \
     bit_array.o \
-    tech_data.o \
-    resource_data.o \
-    building_data.o \
-    city_flags.o \
-    wonder_data.o \
-    small_wonder_data.o \
-    unit_data.o \
-    building_vector.o \
-    wonder_vector.o \
-    small_wonder_vector.o \
-    unit_vector.o \
-    building_assessor.o \
-    wonder_assessor.o \
-    small_wonder_assessor.o \
-    unit_assessor.o \
+    map_bit_overlay.o \
+    map_bit_array_overlay.o \
+    map_terrain_validate.o \
+    map_terrain_data.o \
+    map_loader.o \
+    runtime_trace_dbg.o \
+    general_bit_bank.o \
+    general_assessor.o \
+    effect_ctx.o \
+    effect_enabler.o \
+    booster_effect_register.o \
+    local_unit_exp_booster_register.o \
+    civ_ship_training_booster_register.o \
+    city_commerce_booster_register.o \
+    fort_add_vector.o \
+    mine_add_vector.o \
+    monastery_add_vector.o \
+    outpost_add_vector.o \
+    plantation_add_vector.o \
+    shipyard_add_vector.o \
+    trade_post_add_vector.o \
+    unit_add_vector.o \
+    unit_movement_mng.o \
+    game_array_simple.o \
+    factory_game_array_simple.o \
+    game_state.o \
+    player_ledger.o \
+    civ_relations.o \
+    city_array.o \
     city.o \
-    city_tester.o
+    city_tester.o \
+    -ldl \
+    $LIB_SO \
+    -Wl,-rpath,'$ORIGIN/../data_io'
 
-# Clean up
-rm \
-    str_mng.o \
-    bit_array.o \
-    tech_data.o \
-    resource_data.o \
-    building_data.o \
-    city_flags.o \
-    wonder_data.o \
-    small_wonder_data.o \
-    unit_data.o \
-    building_vector.o \
-    wonder_vector.o \
-    small_wonder_vector.o \
-    unit_vector.o \
-    building_assessor.o \
-    wonder_assessor.o \
-    small_wonder_assessor.o \
-    unit_assessor.o \
-    city.o \
-    city_tester.o
+rm runtime_static_loader.o bit_array.o map_bit_overlay.o map_bit_array_overlay.o \
+    map_terrain_validate.o map_terrain_data.o map_loader.o runtime_trace_dbg.o \
+    general_bit_bank.o general_assessor.o effect_ctx.o effect_enabler.o booster_effect_register.o \
+    local_unit_exp_booster_register.o civ_ship_training_booster_register.o city_commerce_booster_register.o \
+    fort_add_vector.o mine_add_vector.o \
+    monastery_add_vector.o outpost_add_vector.o plantation_add_vector.o \
+    shipyard_add_vector.o trade_post_add_vector.o unit_add_vector.o unit_movement_mng.o \
+    game_array_simple.o factory_game_array_simple.o game_state.o player_ledger.o \
+    civ_relations.o city_array.o city.o city_tester.o
diff --git a/game_engine_dev/game/city_array_comp b/game_engine_dev/game/city_array_comp
--- a/game_engine_dev/game/city_array_comp
+++ b/game_engine_dev/game/city_array_comp
@@ -1,89 +1,46 @@
 #!/bin/bash
+set -e
 
-# Define the include path for the compiler
+cd "$(dirname "$0")"
+
+LIB_SO="../data_io/runtime_static_loader_lib.so"
+if [ ! -f "$LIB_SO" ]; then
+    echo "missing $LIB_SO - run ../data_io/runtime_static_loader_lib_comp first"
+    exit 1
+fi
+
 INC="-I../ \
      -I../misc \
      -I../data_io \
-     -I../wonders \
+     -I../static_state \
      -I../city \
-     -I../small_wonders \
-     -I../units \
-     -I../buildings"
+     -I../dyn_state \
+     -I../gen_bit_banks \
+     -I../game"
+CXXFLAGS="-std=c++17 -Wall -Wextra"
 
-# Compile dependencies
-g++ $INC -c ../misc/str_mng.cpp -o str_mng.o
-g++ $INC -c ../misc/bit_array.cpp -o bit_array.o
-g++ $INC -c ../data_io/tech_data.cpp -o tech_data.o
-g++ $INC -c ../data_io/resource_data.cpp -o resource_data.o
-g++ $INC -c ../data_io/building_data.cpp -o building_data.o
-g++ $INC -c ../data_io/city_flags.cpp -o city_flags.o
-g++ $INC -c ../data_io/wonder_data.cpp -o wonder_data.o
-g++ $INC -c ../data_io/small_wonder_data.cpp -o small_wonder_data.o
-g++ $INC -c ../data_io/unit_data.cpp -o unit_data.o
-g++ $INC -c ../data_io/unit_types.cpp -o unit_types.o
-g++ $INC -c ../data_io/civ_trait_data.cpp -o civ_trait_data.o
-g++ $INC -c ../data_io/civ_data.cpp -o civ_data.o
-g++ $INC -c ../buildings/building_vector.cpp -o building_vector.o
-g++ $INC -c ../wonders/wonder_vector.cpp -o wonder_vector.o
-g++ $INC -c ../small_wonders/small_wonder_vector.cpp -o small_wonder_vector.o
-g++ $INC -c ../units/unit_vector.cpp -o unit_vector.o
-g++ $INC -c ../city/building_assessor.cpp -o building_assessor.o
-g++ $INC -c ../city/wonder_assessor.cpp -o wonder_assessor.o
-g++ $INC -c ../city/small_wonder_assessor.cpp -o small_wonder_assessor.o
-g++ $INC -c ../city/unit_assessor.cpp -o unit_assessor.o
-g++ $INC -c ../city/city.cpp -o city.o
-g++ $INC -c city_array.cpp -o city_array.o
-g++ $INC -c city_array_tester.cpp -o city_array_tester.o
+g++ $CXXFLAGS $INC -c ../data_io/runtime_static_loader.cpp -o runtime_static_loader.o
+g++ $CXXFLAGS $INC -c ../misc/bit_array.cpp -o bit_array.o
+g++ $CXXFLAGS $INC -c ../gen_bit_banks/general_bit_bank.cpp -o general_bit_bank.o
+g++ $CXXFLAGS $INC -c ../city/general_assessor.cpp -o general_assessor.o
+g++ $CXXFLAGS $INC -c ../dyn_state/unit_add_vector.cpp -o unit_add_vector.o
+g++ $CXXFLAGS $INC -c player_ledger.cpp -o player_ledger.o
+g++ $CXXFLAGS $INC -c ../city/city.cpp -o city.o
+g++ $CXXFLAGS $INC -c city_array.cpp -o city_array.o
+g++ $CXXFLAGS $INC -c city_array_tester.cpp -o city_array_tester.o
 
-# Link everything into the final tester
-g++ -o \
-    city_array_tester \
-    str_mng.o \
+g++ $CXXFLAGS -o city_array_tester \
+    runtime_static_loader.o \
     bit_array.o \
-    tech_data.o \
-    resource_data.o \
-    building_data.o \
-    city_flags.o \
-    wonder_data.o \
-    small_wonder_data.o \
-    unit_data.o \
-    unit_types.o \
-    civ_trait_data.o \
-    civ_data.o \
-    building_vector.o \
-    wonder_vector.o \
-    small_wonder_vector.o \
-    unit_vector.o \
-    building_assessor.o \
-    wonder_assessor.o \
-    small_wonder_assessor.o \
-    unit_assessor.o \
+    general_bit_bank.o \
+    general_assessor.o \
+    unit_add_vector.o \
+    player_ledger.o \
     city.o \
     city_array.o \
-    city_array_tester.o
+    city_array_tester.o \
+    -ldl \
+    $LIB_SO \
+    -Wl,-rpath,'$ORIGIN/../data_io'
 
-# Clean up
-rm \
-    str_mng.o \
-    bit_array.o \
-    tech_data.o \
-    resource_data.o \
-    building_data.o \
-    city_flags.o \
-    wonder_data.o \
-    small_wonder_data.o \
-    unit_data.o \
-    unit_types.o \
-    civ_trait_data.o \
-    civ_data.o \
-    building_vector.o \
-    wonder_vector.o \
-    small_wonder_vector.o \
-    unit_vector.o \
-    building_assessor.o \
-    wonder_assessor.o \
-    small_wonder_assessor.o \
-    unit_assessor.o \
-    city.o \
-    city_array.o \
-    city_array_tester.o
+rm runtime_static_loader.o bit_array.o general_bit_bank.o general_assessor.o unit_add_vector.o player_ledger.o city.o city_array.o city_array_tester.o
diff --git a/game_engine_dev/game/game_setup_comp b/game_engine_dev/game/game_setup_comp
--- a/game_engine_dev/game/game_setup_comp
+++ b/game_engine_dev/game/game_setup_comp
@@ -4,8 +4,13 @@ set -e
 cd "$(dirname "$0")"
 
 LIB_SO="../data_io/runtime_static_loader_lib.so"
+MAP_SO="../adv_map_gen/map_gen.so"
 if [ ! -f "$LIB_SO" ]; then
     echo "missing $LIB_SO - run ../data_io/runtime_static_loader_lib_comp first"
+    exit 1
+fi
+if [ ! -f "$MAP_SO" ]; then
+    echo "missing $MAP_SO - run ../adv_map_gen/map_gen_lib_comp first"
     exit 1
 fi
 
@@ -16,6 +21,9 @@ INC="-I.. \
      -I../dyn_state \
      -I../data_io \
      -I../static_state \
+     -I../city \
+     -I../gen_bit_banks \
+     -I../adv_map_gen \
      -I../game"
 CXXFLAGS="-std=c++17 -Wall -Wextra"
 
@@ -40,7 +48,16 @@ g++ $CXXFLAGS $INC -c ../dyn_state/unit_movement_mng.cpp -o unit_movement_mng.o
 g++ $CXXFLAGS $INC -c game_array_simple.cpp -o game_array_simple.o
 g++ $CXXFLAGS $INC -c factory_game_array_simple.cpp -o factory_game_array_simple.o
 g++ $CXXFLAGS $INC -c game_state.cpp -o game_state.o
+g++ $CXXFLAGS $INC -c player_ledger.cpp -o player_ledger.o
 g++ $CXXFLAGS $INC -c civ_relations.cpp -o civ_relations.o
+g++ $CXXFLAGS $INC -c ../adv_map_gen/map_gen_loader.cpp -o map_gen_loader.o
+g++ $CXXFLAGS $INC -c ../gen_bit_banks/general_bit_bank.cpp -o general_bit_bank.o
+g++ $CXXFLAGS $INC -c ../city/city.cpp -o city.o
+g++ $CXXFLAGS $INC -c ../city/general_assessor.cpp -o general_assessor.o
+g++ $CXXFLAGS $INC -c city_array.cpp -o city_array.o
+g++ $CXXFLAGS $INC -c game_helpers/civ_spawner.cpp -o civ_spawner.o
+g++ $CXXFLAGS $INC -c game_loop_cache.cpp -o game_loop_cache.o
+g++ $CXXFLAGS $INC -c game_loop.cpp -o game_loop.o
 g++ $CXXFLAGS $INC -c game_setup.cpp -o game_setup.o
 g++ $CXXFLAGS $INC -c game_setup_tester.cpp -o game_setup_tester.o
 
@@ -66,7 +83,16 @@ g++ $CXXFLAGS -o game_setup_tester \
     game_array_simple.o \
     factory_game_array_simple.o \
     game_state.o \
+    player_ledger.o \
     civ_relations.o \
+    map_gen_loader.o \
+    city.o \
+    general_bit_bank.o \
+    general_assessor.o \
+    city_array.o \
+    civ_spawner.o \
+    game_loop_cache.o \
+    game_loop.o \
     game_setup.o \
     game_setup_tester.o \
     -ldl \
@@ -79,5 +105,6 @@ rm runtime_static_loader.o map_terrain_validate.o map_terrain_data.o map_loader.
     fort_add_vector.o mine_add_vector.o monastery_add_vector.o \
     outpost_add_vector.o plantation_add_vector.o shipyard_add_vector.o \
     trade_post_add_vector.o unit_add_vector.o unit_movement_mng.o \
-    game_array_simple.o factory_game_array_simple.o game_state.o \
-    civ_relations.o game_setup.o game_setup_tester.o
+    game_array_simple.o factory_game_array_simple.o game_state.o player_ledger.o \
+    civ_relations.o game_setup.o game_setup_tester.o map_gen_loader.o \
+    city.o general_bit_bank.o general_assessor.o city_array.o civ_spawner.o game_loop_cache.o game_loop.o
