Wind and rain in map generator

diff --git a/game_engine_dev/game/game_setup_comp b/game_engine_dev/game/game_setup_comp
--- a/game_engine_dev/game/game_setup_comp
+++ b/game_engine_dev/game/game_setup_comp
@@ -1,22 +1,83 @@
 #!/bin/bash
+set -e
 
-INC="-I.. -I../map_loader -I../simple_map_gen"
+cd "$(dirname "$0")"
+
+LIB_SO="../data_io/runtime_static_loader_lib.so"
+if [ ! -f "$LIB_SO" ]; then
+    echo "missing $LIB_SO - run ../data_io/runtime_static_loader_lib_comp first"
+    exit 1
+fi
+
+INC="-I.. \
+     -I../misc \
+     -I../map_loader \
+     -I../simple_map_gen \
+     -I../dyn_state \
+     -I../data_io \
+     -I../static_state \
+     -I../game"
 CXXFLAGS="-std=c++17 -Wall -Wextra"
 
+g++ $CXXFLAGS $INC -c ../data_io/runtime_static_loader.cpp -o runtime_static_loader.o
 g++ $CXXFLAGS $INC -c ../map_loader/map_terrain_validate.cpp -o map_terrain_validate.o
 g++ $CXXFLAGS $INC -c ../map_loader/map_terrain_data.cpp -o map_terrain_data.o
 g++ $CXXFLAGS $INC -c ../map_loader/map_loader.cpp -o map_loader.o
 g++ $CXXFLAGS $INC -c ../map_loader/starting_point_generator.cpp -o starting_point_generator.o
+g++ $CXXFLAGS $INC -c runtime_trace_dbg.cpp -o runtime_trace_dbg.o
+g++ $CXXFLAGS $INC -c ../misc/map_bit_overlay.cpp -o map_bit_overlay.o
+g++ $CXXFLAGS $INC -c ../misc/map_bit_array_overlay.cpp -o map_bit_array_overlay.o
+g++ $CXXFLAGS $INC -c ../misc/bit_array.cpp -o bit_array.o
+g++ $CXXFLAGS $INC -c ../dyn_state/fort_add_vector.cpp -o fort_add_vector.o
+g++ $CXXFLAGS $INC -c ../dyn_state/mine_add_vector.cpp -o mine_add_vector.o
+g++ $CXXFLAGS $INC -c ../dyn_state/monastery_add_vector.cpp -o monastery_add_vector.o
+g++ $CXXFLAGS $INC -c ../dyn_state/outpost_add_vector.cpp -o outpost_add_vector.o
+g++ $CXXFLAGS $INC -c ../dyn_state/plantation_add_vector.cpp -o plantation_add_vector.o
+g++ $CXXFLAGS $INC -c ../dyn_state/shipyard_add_vector.cpp -o shipyard_add_vector.o
+g++ $CXXFLAGS $INC -c ../dyn_state/trade_post_add_vector.cpp -o trade_post_add_vector.o
+g++ $CXXFLAGS $INC -c ../dyn_state/unit_add_vector.cpp -o unit_add_vector.o
+g++ $CXXFLAGS $INC -c ../dyn_state/unit_movement_mng.cpp -o unit_movement_mng.o
+g++ $CXXFLAGS $INC -c game_array_simple.cpp -o game_array_simple.o
+g++ $CXXFLAGS $INC -c factory_game_array_simple.cpp -o factory_game_array_simple.o
+g++ $CXXFLAGS $INC -c game_state.cpp -o game_state.o
+g++ $CXXFLAGS $INC -c civ_relations.cpp -o civ_relations.o
 g++ $CXXFLAGS $INC -c game_setup.cpp -o game_setup.o
 g++ $CXXFLAGS $INC -c game_setup_tester.cpp -o game_setup_tester.o
 
 g++ $CXXFLAGS -o game_setup_tester \
+    runtime_static_loader.o \
     map_terrain_validate.o \
     map_terrain_data.o \
     map_loader.o \
     starting_point_generator.o \
+    runtime_trace_dbg.o \
+    map_bit_overlay.o \
+    map_bit_array_overlay.o \
+    bit_array.o \
+    fort_add_vector.o \
+    mine_add_vector.o \
+    monastery_add_vector.o \
+    outpost_add_vector.o \
+    plantation_add_vector.o \
+    shipyard_add_vector.o \
+    trade_post_add_vector.o \
+    unit_add_vector.o \
+    unit_movement_mng.o \
+    game_array_simple.o \
+    factory_game_array_simple.o \
+    game_state.o \
+    civ_relations.o \
     game_setup.o \
-    game_setup_tester.o
+    game_setup_tester.o \
+    -ldl \
+    $LIB_SO \
+    -Wl,-rpath,'$ORIGIN/../data_io'
 
-rm map_terrain_validate.o map_terrain_data.o map_loader.o \
-    starting_point_generator.o game_setup.o game_setup_tester.o
+rm runtime_static_loader.o map_terrain_validate.o map_terrain_data.o map_loader.o \
+    starting_point_generator.o runtime_trace_dbg.o map_bit_overlay.o \
+    map_bit_array_overlay.o bit_array.o \
+    fort_add_vector.o mine_add_vector.o monastery_add_vector.o \
+    outpost_add_vector.o plantation_add_vector.o shipyard_add_vector.o \
+    trade_post_add_vector.o unit_add_vector.o unit_movement_mng.o \
+    game_array_simple.o factory_game_array_simple.o game_state.o \
+    civ_relations.o game_setup.o game_setup_tester.o
